package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

const flatPlaylistSample = `{"title": "You Don't Know Me (feat. Duane Harden) (Radio Edit)", "channel": "Armand Van Helden - Topic", "uploader": "Armand Van Helden - Topic", "id": "rnlp_avexYQ", "url": "https://www.youtube.com/watch?v=rnlp_avexYQ", "playlist": "90s UK Dance Hits", "playlist_title": "90s UK Dance Hits", "playlist_id": "PLnEEDxeHD6BPvM-iOmSeKx5N6Uug3vZQa", "playlist_index": 1, "playlist_count": 90}

{"title": "Modjo - Lady (Hear Me Tonight)", "channel": "ModjoOfficial", "uploader": "ModjoOfficial", "id": "MR3uP7IYz44", "url": "https://www.youtube.com/watch?v=MR3uP7IYz44", "playlist": "90s UK Dance Hits", "playlist_title": "90s UK Dance Hits", "playlist_id": "PLnEEDxeHD6BPvM-iOmSeKx5N6Uug3vZQa", "playlist_index": 3, "playlist_count": 90}
`

func TestParsePlaylistEntries(t *testing.T) {
	entries, err := parsePlaylistEntries(strings.NewReader(flatPlaylistSample))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("want 2 entries, got %d", len(entries))
	}
	if entries[0].ID != "rnlp_avexYQ" || entries[0].PlaylistIndex != 1 || entries[0].PlaylistTitle != "90s UK Dance Hits" || entries[0].PlaylistCount != 90 {
		t.Errorf("unexpected first entry: %+v", entries[0])
	}
	if !isAutoGenerated(entries[0]) {
		t.Errorf("Topic upload should be detected as auto-generated")
	}
	if isAutoGenerated(entries[1]) {
		t.Errorf("artist channel upload must not be treated as auto-generated")
	}
	if !isAutoGenerated(PlaylistEntry{ID: "x"}) {
		t.Errorf("entries without channel info should still be resolved")
	}
}

// nextResponse builds an innertube "next" style document. musicID is the
// video linked from the Music card, descID a watch link in the description
// text, relatedID a recommended video that must never be picked.
func nextResponse(selfID, musicID, descID, relatedID string) []byte {
	doc := map[string]interface{}{
		"contents": map[string]interface{}{
			"twoColumnWatchNextResults": map[string]interface{}{
				"secondaryResults": []interface{}{
					map[string]interface{}{"compactVideoRenderer": map[string]interface{}{"videoId": relatedID}},
				},
			},
		},
		"currentVideoEndpoint": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": selfID}},
		"engagementPanels": []interface{}{
			map[string]interface{}{
				"engagementPanelSectionListRenderer": map[string]interface{}{
					"panelIdentifier": "engagement-panel-structured-description",
					"content": map[string]interface{}{
						"structuredDescriptionContentRenderer": map[string]interface{}{
							"items": []interface{}{
								map[string]interface{}{
									"expandableVideoDescriptionBodyRenderer": map[string]interface{}{
										"attributedDescriptionBodyText": map[string]interface{}{
											"content": "Provided to YouTube.\nOfficial video: https://youtu.be/" + descID + "\nAuto-generated by YouTube.",
											"commandRuns": []interface{}{
												map[string]interface{}{"onTap": map[string]interface{}{"innertubeCommand": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": descID}}}},
											},
										},
									},
								},
								map[string]interface{}{
									"videoDescriptionMusicSectionRenderer": map[string]interface{}{
										"sectionTitle": map[string]interface{}{"simpleText": "Music"},
										"carouselLockups": []interface{}{
											map[string]interface{}{
												"carouselLockupRenderer": map[string]interface{}{
													"videoLockup": map[string]interface{}{
														"compactVideoRenderer": map[string]interface{}{
															"videoId":            musicID,
															"navigationEndpoint": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": musicID}},
														},
													},
													"infoRows": []interface{}{
														map[string]interface{}{"infoRowRenderer": map[string]interface{}{"title": map[string]interface{}{"simpleText": "SONG"}}},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
	b, _ := json.Marshal(doc)
	return b
}

func TestCandidatesFromInitialData(t *testing.T) {
	raw := nextResponse("rnlp_avexYQ", "-bsONE-kZwI", "dEsCrIpTi0n", "rElAtEd0000")
	got := candidatesFromInitialData(raw, "rnlp_avexYQ")
	want := []string{"-bsONE-kZwI", "dEsCrIpTi0n"}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Fatalf("want %v, got %v", want, got)
	}

	// Music card pointing at the video itself must be ignored.
	raw = nextResponse("rnlp_avexYQ", "rnlp_avexYQ", "", "rElAtEd0000")
	if got := candidatesFromInitialData(raw, "rnlp_avexYQ"); len(got) != 0 {
		t.Fatalf("self link should be ignored, got %v", got)
	}
}

func watchPage(selfID, musicID, descID string) string {
	initial := string(nextResponse(selfID, musicID, descID, "rElAtEd0000"))
	player := `{"videoDetails":{"videoId":"` + selfID + `","shortDescription":"Tricky };</script> inside a string\nhttps://www.youtube.com/watch?v=` + descID + `&t=1"}}`
	return `<!DOCTYPE html><html><head><script>ytcfg.set({"INNERTUBE_CONTEXT":{"client":{"clientName":"WEB","clientVersion":"2.20261001.01.00"}},"INNERTUBE_CONTEXT_CLIENT_NAME":1});</script>` +
		`<script>var ytInitialPlayerResponse = ` + player + `;</script>` +
		`<script>var ytInitialData = ` + initial + `;</script></head><body></body></html>`
}

func TestCandidatesFromWatchPage(t *testing.T) {
	got := candidatesFromWatchPage([]byte(watchPage("rnlp_avexYQ", "-bsONE-kZwI", "dEsCrIpTi0n")), "rnlp_avexYQ")
	want := []string{"-bsONE-kZwI", "dEsCrIpTi0n"}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Fatalf("want %v, got %v", want, got)
	}

	// Stripped down page (what YouTube serves when it dislikes the client):
	// only the player response is there and the description has no links.
	stripped := `<script>var ytInitialPlayerResponse = {"videoDetails":{"shortDescription":"nothing here"}};</script>`
	if got := candidatesFromWatchPage([]byte(stripped), "rnlp_avexYQ"); len(got) != 0 {
		t.Fatalf("expected no candidates, got %v", got)
	}
}

func TestExtractJSONAfter(t *testing.T) {
	if extractJSONAfter([]byte("no marker"), "var x = ") != nil {
		t.Error("missing marker must return nil")
	}
	got := extractJSONAfter([]byte(`var x = {"a":"};</script>","b":[1,2]};</script>`), "var x = ")
	if string(got) != `{"a":"};</script>","b":[1,2]}` {
		t.Errorf("unexpected value: %s", got)
	}
}

// fakeYouTube serves a watch page, the innertube next endpoint and oEmbed.
type fakeYouTube struct {
	pages   map[string]string // video id -> watch page HTML
	next    map[string][]byte // video id -> next response
	authors map[string]string // video id -> channel name (missing = 404)
	hits    map[string]int
}

func (f *fakeYouTube) server(t *testing.T) (*httptest.Server, *OfficialResolver) {
	f.hits = map[string]int{}
	mux := http.NewServeMux()
	mux.HandleFunc("/watch", func(w http.ResponseWriter, r *http.Request) {
		id := r.URL.Query().Get("v")
		f.hits["watch"]++
		if page, ok := f.pages[id]; ok {
			w.Write([]byte(page))
			return
		}
		http.NotFound(w, r)
	})
	mux.HandleFunc("/youtubei/v1/next", func(w http.ResponseWriter, r *http.Request) {
		f.hits["next"]++
		var body struct {
			VideoID string `json:"videoId"`
		}
		json.NewDecoder(r.Body).Decode(&body)
		if r.Header.Get("X-YouTube-Client-Version") == "" {
			t.Errorf("next request without client version header")
		}
		if resp, ok := f.next[body.VideoID]; ok {
			w.Write(resp)
			return
		}
		w.Write([]byte(`{}`))
	})
	mux.HandleFunc("/oembed", func(w http.ResponseWriter, r *http.Request) {
		f.hits["oembed"]++
		u := r.URL.Query().Get("url")
		id := u[strings.LastIndex(u, "=")+1:]
		if author, ok := f.authors[id]; ok {
			json.NewEncoder(w).Encode(map[string]string{"author_name": author})
			return
		}
		http.NotFound(w, r)
	})
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)

	res := newOfficialResolver(func(string, ...interface{}) {})
	res.Client = srv.Client()
	res.WatchBase = srv.URL + "/watch?v="
	res.NextURL = srv.URL + "/youtubei/v1/next"
	res.OEmbedURL = srv.URL + "/oembed?format=json&url="
	res.Attempts = 1
	return srv, res
}

func TestResolveFromWatchPage(t *testing.T) {
	f := &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "-bsONE-kZwI", "")},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res := f.server(t)
	got, reason := res.Resolve("rnlp_avexYQ")
	if got != "-bsONE-kZwI" {
		t.Fatalf("want -bsONE-kZwI, got %q (%s)", got, reason)
	}
	if f.hits["next"] != 0 {
		t.Errorf("next endpoint should not be needed when the page has the Music card")
	}
}

func TestResolveFallsBackToNext(t *testing.T) {
	f := &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": `<script>var ytInitialPlayerResponse = {"videoDetails":{"shortDescription":"stripped"}};</script>`},
		next:    map[string][]byte{"rnlp_avexYQ": nextResponse("rnlp_avexYQ", "-bsONE-kZwI", "", "rElAtEd0000")},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res := f.server(t)
	got, reason := res.Resolve("rnlp_avexYQ")
	if got != "-bsONE-kZwI" {
		t.Fatalf("want -bsONE-kZwI, got %q (%s)", got, reason)
	}
	if f.hits["next"] != 1 {
		t.Errorf("expected one next request, got %d", f.hits["next"])
	}
}

func TestResolveSkipsTopicAndDeadLinks(t *testing.T) {
	f := &fakeYouTube{
		pages: map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "aNoThErT0p1", "dEsCrIpTi0n")},
		authors: map[string]string{
			"aNoThErT0p1": "Armand Van Helden - Topic",
			"dEsCrIpTi0n": "Armand Van Helden",
		},
	}
	_, res := f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "dEsCrIpTi0n" {
		t.Fatalf("Topic candidate should be skipped in favour of the description link, got %q", got)
	}

	// Candidate that no longer exists, nothing else linked: keep original.
	f = &fakeYouTube{pages: map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "gOnEgOnEgOn", "")}}
	_, res = f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "" {
		t.Fatalf("dead candidate must not be returned, got %q", got)
	}

	// Watch page unavailable and next empty: keep original.
	f = &fakeYouTube{}
	_, res = f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "" {
		t.Fatalf("expected empty result, got %q", got)
	}
}

func TestApplyPlaylistFields(t *testing.T) {
	e := PlaylistEntry{
		Playlist:      "90s UK Dance Hits: Vol/1",
		PlaylistTitle: "90s UK Dance Hits: Vol/1",
		PlaylistID:    "PLnEEDxeHD6BPvM-iOmSeKx5N6Uug3vZQa",
		PlaylistIndex: 7,
		PlaylistCount: 90,
	}
	cases := map[string]string{
		"%(playlist_title,playlist)s/%(playlist_index)02d - %(title)s.%(ext)s": "90s UK Dance Hits： Vol⧸1/07 - %(title)s.%(ext)s",
		"%(title)s.%(ext)s": "%(title)s.%(ext)s",
		"%(playlist)s/%(playlist_index)s of %(playlist_count)d.%(ext)s": "90s UK Dance Hits： Vol⧸1/7 of 90.%(ext)s",
		"%(playlist_id)s/%(playlist_index)03d.%(ext)s":                  "PLnEEDxeHD6BPvM-iOmSeKx5N6Uug3vZQa/007.%(ext)s",
		"%(playlist_uploader)s/%(title)s.%(ext)s":                       "%(playlist_uploader)s/%(title)s.%(ext)s",
		"%(playlist_title|Singles)s/%(title)s.%(ext)s":                  "90s UK Dance Hits： Vol⧸1/%(title)s.%(ext)s",
	}
	for in, want := range cases {
		if got := applyPlaylistFields(in, e); got != want {
			t.Errorf("template %q:\n want %q\n got  %q", in, want, got)
		}
	}

	empty := PlaylistEntry{}
	if got := applyPlaylistFields("%(playlist_title|Singles)s/%(playlist_index)02d.%(ext)s", empty); got != "Singles/NA.%(ext)s" {
		t.Errorf("defaults: got %q", got)
	}
}

func TestSanitizeFilename(t *testing.T) {
	cases := map[string]string{
		`AC/DC: "Back" <in> Black?*|\`: "AC⧸DC： ＂Back＂ ＜in＞ Black？＊｜⧹",
		"trailing dots... ":            "trailing dots",
		"":                             "_",
		"line\nbreak":                  "line break",
	}
	for in, want := range cases {
		if got := sanitizeFilename(in); got != want {
			t.Errorf("%q: want %q, got %q", in, want, got)
		}
	}
}

func TestParseBoolAndConfig(t *testing.T) {
	for _, v := range []string{"true", "True", "yes", "1", "on"} {
		if !parseBool(v) {
			t.Errorf("%q should be true", v)
		}
	}
	for _, v := range []string{"false", "0", "no", "", "maybe"} {
		if parseBool(v) {
			t.Errorf("%q should be false", v)
		}
	}

	dir := t.TempDir()
	path := dir + "/setup.conf"
	if err := os.WriteFile(path, []byte("download_official_music_video = true\nquality=best\n"), 0644); err != nil {
		t.Fatal(err)
	}
	cfg, err := loadSetupConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.DownloadOfficialMusicVideo || cfg.Quality != "best" {
		t.Errorf("unexpected config: %+v", cfg)
	}
	if defaultConfig().DownloadOfficialMusicVideo {
		t.Error("official video mode must be off by default")
	}
}

func TestBuildDownloadArgs(t *testing.T) {
	cfg := Config{Quality: "best", MergeOutputFormat: "mp4", ExtraArgs: []string{"-4"}}
	got := buildDownloadArgs(cfg, "out/%(title)s.%(ext)s", "https://www.youtube.com/watch?v=abc")
	want := "-f best -o out/%(title)s.%(ext)s --merge-output-format mp4 -4 https://www.youtube.com/watch?v=abc"
	if strings.Join(got, " ") != want {
		t.Errorf("want %q, got %q", want, strings.Join(got, " "))
	}
}
