package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// PlaylistEntry is one line of `yt-dlp --flat-playlist -j <playlist>`.
type PlaylistEntry struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Channel       string `json:"channel"`
	Uploader      string `json:"uploader"`
	URL           string `json:"url"`
	Playlist      string `json:"playlist"`
	PlaylistTitle string `json:"playlist_title"`
	PlaylistID    string `json:"playlist_id"`
	PlaylistIndex int    `json:"playlist_index"`
	PlaylistCount int    `json:"playlist_count"`
}

// listPlaylistEntries asks yt-dlp for the playlist contents without
// downloading anything. One JSON object per line is returned.
func listPlaylistEntries(ytDlpPath, playlistURL string, extraArgs []string) ([]PlaylistEntry, error) {
	args := []string{"--flat-playlist", "-j", "--no-warnings"}
	args = append(args, extraArgs...)
	args = append(args, playlistURL)

	cmd := exec.Command(ytDlpPath, args...)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil && len(out) == 0 {
		return nil, fmt.Errorf("yt-dlp --flat-playlist failed: %w", err)
	}

	return parsePlaylistEntries(bytes.NewReader(out))
}

func parsePlaylistEntries(r io.Reader) ([]PlaylistEntry, error) {
	var entries []PlaylistEntry
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 1024*1024), 16*1024*1024)
	for scanner.Scan() {
		line := bytes.TrimSpace(scanner.Bytes())
		if len(line) == 0 {
			continue
		}
		var e PlaylistEntry
		if err := json.Unmarshal(line, &e); err != nil {
			return nil, fmt.Errorf("cannot parse yt-dlp playlist entry: %w", err)
		}
		if e.ID == "" {
			continue
		}
		entries = append(entries, e)
	}
	return entries, scanner.Err()
}

// isTopicChannel reports whether a channel name is one of YouTube's
// auto-generated "<Artist> - Topic" channels (the art-track uploads).
func isTopicChannel(name string) bool {
	return strings.HasSuffix(strings.TrimSpace(name), " - Topic")
}

// isAutoGenerated reports whether a playlist entry is an auto-generated
// art track (uploaded by a "- Topic" channel). If yt-dlp gave us no channel
// information at all, we return true so the caller still tries to resolve.
func isAutoGenerated(e PlaylistEntry) bool {
	if e.Channel == "" && e.Uploader == "" {
		return true
	}
	return isTopicChannel(e.Channel) || isTopicChannel(e.Uploader)
}

// OfficialResolver finds the official music video that YouTube links from
// the "Music" card in the description of an auto-generated art track.
type OfficialResolver struct {
	Client    *http.Client
	WatchBase string // e.g. https://www.youtube.com/watch?v=
	NextURL   string // innertube "next" endpoint
	OEmbedURL string // e.g. https://www.youtube.com/oembed?format=json&url=
	UserAgent string
	Attempts  int
	Log       func(format string, a ...interface{})
}

func newOfficialResolver(log func(format string, a ...interface{})) *OfficialResolver {
	return &OfficialResolver{
		Client:    &http.Client{Timeout: 45 * time.Second},
		WatchBase: "https://www.youtube.com/watch?v=",
		NextURL:   "https://www.youtube.com/youtubei/v1/next?prettyPrint=false",
		OEmbedURL: "https://www.youtube.com/oembed?format=json&url=",
		UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
		Attempts:  3,
		Log:       log,
	}
}

var videoIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{11}$`)

// youtubeLinkPattern finds watch links inside free text (description).
var youtubeLinkPattern = regexp.MustCompile(`(?:youtube\.com/watch\?(?:[^\s"&]*&)?v=|youtu\.be/|youtube\.com/shorts/)([A-Za-z0-9_-]{11})`)

// Resolve returns the video id of the official music video linked from the
// given art track, or "" when none could be found. The returned reason is a
// short human readable explanation for logging.
func (r *OfficialResolver) Resolve(videoID string) (string, string) {
	return r.ResolveLog(videoID, r.Log)
}

// ResolveLog is Resolve with a per-call log function, so concurrent
// callers can route messages to their own entry.
func (r *OfficialResolver) ResolveLog(videoID string, logFn func(format string, a ...interface{})) (string, string) {
	logf := func(format string, a ...interface{}) {
		if logFn != nil {
			logFn(format+"\n", a...)
		}
	}
	var candidates []string

	// 1. Crawl the watch page like a browser would.
	html, err := r.get(r.WatchBase + videoID)
	if err != nil {
		logf("[official] %s: cannot fetch watch page: %v", videoID, err)
	} else {
		candidates = append(candidates, candidatesFromWatchPage(html, videoID)...)
	}

	// 2. The watch page sometimes ships a stripped down description panel.
	//    The innertube "next" call is what the page itself uses to fill it.
	if len(candidates) == 0 {
		nextJSON, err := r.fetchNext(videoID, html)
		if err != nil {
			logf("[official] %s: innertube next request failed: %v", videoID, err)
		} else {
			candidates = append(candidates, candidatesFromInitialData(nextJSON, videoID)...)
		}
	}

	if len(candidates) == 0 {
		return "", "no official video link found in description"
	}

	for _, cand := range uniqueStrings(candidates) {
		author, ok, err := r.lookupAuthor(cand)
		switch {
		case err != nil:
			// oEmbed can refuse (401) for videos that disallow embedding.
			// The link came from YouTube itself, so accept it.
			logf("[official] %s: oembed check for %s inconclusive (%v), accepting", videoID, cand, err)
			return cand, "linked from description (unverified channel)"
		case !ok:
			logf("[official] %s: candidate %s does not exist, skipping", videoID, cand)
		case isTopicChannel(author):
			logf("[official] %s: candidate %s is another auto-generated track (%s), skipping", videoID, cand, author)
		default:
			return cand, fmt.Sprintf("official video by %q", author)
		}
	}

	return "", "linked videos were not official uploads"
}

func (r *OfficialResolver) do(req *http.Request) ([]byte, int, error) {
	req.Header.Set("User-Agent", r.UserAgent)
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	// Skip the EU cookie consent interstitial.
	req.Header.Set("Cookie", "SOCS=CAI; CONSENT=YES+cb")

	attempts := r.Attempts
	if attempts < 1 {
		attempts = 1
	}

	var lastErr error
	for i := 0; i < attempts; i++ {
		if i > 0 {
			time.Sleep(time.Duration(1<<uint(i)) * time.Second)
		}
		resp, err := r.Client.Do(req)
		if err != nil {
			lastErr = err
			continue
		}
		body, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			lastErr = err
			continue
		}
		if resp.StatusCode == http.StatusTooManyRequests || resp.StatusCode >= 500 {
			lastErr = fmt.Errorf("HTTP status %s", resp.Status)
			continue
		}
		return body, resp.StatusCode, nil
	}
	return nil, 0, lastErr
}

func (r *OfficialResolver) get(url string) ([]byte, error) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	body, status, err := r.do(req)
	if err != nil {
		return nil, err
	}
	if status != http.StatusOK {
		return nil, fmt.Errorf("HTTP status %d", status)
	}
	return body, nil
}

// fetchNext calls the innertube "next" endpoint for a video. The client
// context is taken from the watch page when available so the request looks
// like the one the page itself makes.
func (r *OfficialResolver) fetchNext(videoID string, pageHTML []byte) ([]byte, error) {
	ctx := map[string]interface{}{
		"client": map[string]interface{}{
			"clientName":    "WEB",
			"clientVersion": "2.20240101.00.00",
			"hl":            "en",
			"gl":            "US",
		},
	}
	clientVersion := "2.20240101.00.00"
	if pageHTML != nil {
		if raw := extractJSONAfter(pageHTML, `"INNERTUBE_CONTEXT":`); raw != nil {
			var pageCtx map[string]interface{}
			if json.Unmarshal(raw, &pageCtx) == nil {
				ctx = pageCtx
				if c, ok := pageCtx["client"].(map[string]interface{}); ok {
					if v, ok := c["clientVersion"].(string); ok && v != "" {
						clientVersion = v
					}
				}
			}
		}
	}

	payload, err := json.Marshal(map[string]interface{}{
		"context": ctx,
		"videoId": videoID,
	})
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", r.NextURL, bytes.NewReader(payload))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Origin", "https://www.youtube.com")
	req.Header.Set("Referer", r.WatchBase+videoID)
	req.Header.Set("X-YouTube-Client-Name", "1")
	req.Header.Set("X-YouTube-Client-Version", clientVersion)

	body, status, err := r.do(req)
	if err != nil {
		return nil, err
	}
	if status != http.StatusOK {
		return nil, fmt.Errorf("HTTP status %d", status)
	}
	return body, nil
}

// lookupAuthor asks the oEmbed endpoint who uploaded a video.
// ok=false means the video does not exist (404).
func (r *OfficialResolver) lookupAuthor(videoID string) (author string, ok bool, err error) {
	body, err := func() ([]byte, error) {
		req, err := http.NewRequest("GET", r.OEmbedURL+"https://www.youtube.com/watch?v="+videoID, nil)
		if err != nil {
			return nil, err
		}
		body, status, err := r.do(req)
		if err != nil {
			return nil, err
		}
		if status == http.StatusNotFound {
			return nil, nil
		}
		if status != http.StatusOK {
			return nil, fmt.Errorf("HTTP status %d", status)
		}
		return body, nil
	}()
	if err != nil {
		return "", false, err
	}
	if body == nil {
		return "", false, nil
	}
	var o struct {
		AuthorName string `json:"author_name"`
	}
	if err := json.Unmarshal(body, &o); err != nil {
		return "", false, err
	}
	return o.AuthorName, true, nil
}

// extractJSONAfter finds `marker` in data and decodes the single JSON value
// that follows it. It returns nil when the marker is absent or the value is
// not valid JSON.
func extractJSONAfter(data []byte, marker string) []byte {
	idx := bytes.Index(data, []byte(marker))
	if idx < 0 {
		return nil
	}
	rest := data[idx+len(marker):]
	dec := json.NewDecoder(bytes.NewReader(rest))
	var v json.RawMessage
	if err := dec.Decode(&v); err != nil {
		return nil
	}
	return v
}

// candidatesFromWatchPage extracts official-video candidates from the raw
// HTML of a watch page, most trustworthy first.
func candidatesFromWatchPage(html []byte, selfID string) []string {
	var out []string
	if raw := extractJSONAfter(html, "var ytInitialData = "); raw != nil {
		out = append(out, candidatesFromInitialData(raw, selfID)...)
	} else if raw := extractJSONAfter(html, `window["ytInitialData"] = `); raw != nil {
		out = append(out, candidatesFromInitialData(raw, selfID)...)
	}
	if raw := extractJSONAfter(html, "var ytInitialPlayerResponse = "); raw != nil {
		var pr struct {
			VideoDetails struct {
				ShortDescription string `json:"shortDescription"`
			} `json:"videoDetails"`
		}
		if json.Unmarshal(raw, &pr) == nil {
			out = append(out, linksInText(pr.VideoDetails.ShortDescription, selfID)...)
		}
	}
	return uniqueStrings(out)
}

// candidatesFromInitialData walks a ytInitialData / innertube "next"
// response. Priority:
//  1. video ids inside the "Music" card of the description panel
//  2. any other video linked from the structured description panel
//  3. watch links written as plain text in the description
func candidatesFromInitialData(raw []byte, selfID string) []string {
	var root interface{}
	if err := json.Unmarshal(raw, &root); err != nil {
		return nil
	}

	var music, panel, text []string

	var walk func(node interface{}, inMusic, inPanel bool)
	walk = func(node interface{}, inMusic, inPanel bool) {
		switch n := node.(type) {
		case map[string]interface{}:
			if id, ok := n["panelIdentifier"].(string); ok && id == "engagement-panel-structured-description" {
				inPanel = true
			}
			if inPanel {
				if s, ok := n["videoId"].(string); ok && videoIDPattern.MatchString(s) && s != selfID {
					if inMusic {
						music = append(music, s)
					} else {
						panel = append(panel, s)
					}
				}
				for _, key := range []string{"content", "simpleText", "text"} {
					if s, ok := n[key].(string); ok {
						text = append(text, linksInText(s, selfID)...)
					}
				}
			}
			for k, v := range n {
				walk(v, inMusic || isMusicSectionKey(k), inPanel)
			}
		case []interface{}:
			for _, v := range n {
				walk(v, inMusic, inPanel)
			}
		}
	}
	walk(root, false, false)

	return uniqueStrings(append(append(music, panel...), text...))
}

// isMusicSectionKey matches the renderers YouTube has used for the
// "Music" card at the bottom of a description.
func isMusicSectionKey(key string) bool {
	switch key {
	case "videoDescriptionMusicSectionRenderer",
		"videoAttributeViewModel",
		"horizontalCardListRenderer",
		"carouselLockupRenderer":
		return true
	}
	return false
}

func linksInText(text, selfID string) []string {
	var out []string
	for _, m := range youtubeLinkPattern.FindAllStringSubmatch(text, -1) {
		if m[1] != selfID {
			out = append(out, m[1])
		}
	}
	return out
}

func uniqueStrings(in []string) []string {
	seen := make(map[string]bool, len(in))
	var out []string
	for _, s := range in {
		if s == "" || seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

// --- output template handling ------------------------------------------

var templateFieldPattern = regexp.MustCompile(`%\(([A-Za-z0-9_,|]+)\)([-+ 0#]*\d*)([sd])`)

// applyPlaylistFields pre-renders the playlist related fields of a yt-dlp
// output template. When a single video is downloaded on its own, yt-dlp
// has no playlist context, so %(playlist_title)s and friends would become
// "NA". We substitute them with what the flat playlist listing told us, so
// files land in the same place they would with a normal playlist download.
func applyPlaylistFields(template string, e PlaylistEntry) string {
	return templateFieldPattern.ReplaceAllStringFunc(template, func(match string) string {
		sub := templateFieldPattern.FindStringSubmatch(match)
		expr, flags, verb := sub[1], sub[2], sub[3]

		defaultValue := ""
		hasDefault := false
		if i := strings.Index(expr, "|"); i >= 0 {
			defaultValue = expr[i+1:]
			hasDefault = true
			expr = expr[:i]
		}

		var strVal string
		var intVal int
		isInt := false
		found := false

		for _, field := range strings.Split(expr, ",") {
			field = strings.TrimSpace(field)
			switch field {
			case "playlist_title":
				strVal = e.PlaylistTitle
			case "playlist":
				strVal = e.Playlist
				if strVal == "" {
					strVal = e.PlaylistTitle
				}
			case "playlist_id":
				strVal = e.PlaylistID
			case "playlist_index", "playlist_autonumber":
				intVal, isInt = e.PlaylistIndex, true
			case "playlist_count":
				intVal, isInt = e.PlaylistCount, true
			default:
				// Not a playlist field: leave the whole placeholder to yt-dlp.
				return match
			}
			if (isInt && intVal != 0) || (!isInt && strVal != "") {
				found = true
				break
			}
			isInt = false
		}

		if !found {
			if hasDefault {
				return defaultValue
			}
			return "NA"
		}

		if isInt {
			if verb == "d" {
				return fmt.Sprintf("%"+flags+"d", intVal)
			}
			return fmt.Sprintf("%"+flags+"s", strconv.Itoa(intVal))
		}
		if verb == "d" {
			return match
		}
		return fmt.Sprintf("%"+flags+"s", sanitizeFilename(strVal))
	})
}

// sanitizeFilename mirrors yt-dlp's default (non restricted) filename
// sanitisation so that folder names match between both download modes.
func sanitizeFilename(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '/':
			b.WriteRune('⧸') // ⧸
		case '\\':
			b.WriteRune('⧹') // ⧹
		case '"', '*', ':', '<', '>', '?', '|':
			b.WriteRune(r + 0xFEE0) // full-width variant
		case '\n', '\r', '\t':
			b.WriteRune(' ')
		default:
			if r < 32 || r == 127 {
				continue
			}
			b.WriteRune(r)
		}
	}
	out := strings.TrimRight(b.String(), ". ")
	out = strings.TrimSpace(out)
	if out == "" {
		return "_"
	}
	return out
}
