package official

import (
	"fmt"
	"net/http"
	"time"
)

// LogFunc receives progress messages, printf style.
type LogFunc func(format string, a ...interface{})

// Resolver crawls YouTube to find the official music video of an art track.
type Resolver struct {
	Client    *http.Client
	WatchBase string // e.g. https://www.youtube.com/watch?v=
	NextURL   string // innertube "next" endpoint
	OEmbedURL string // e.g. https://www.youtube.com/oembed?format=json&url=
	UserAgent string
	Attempts  int
	Log       LogFunc
}

// NewResolver returns a resolver pointed at the real YouTube endpoints.
func NewResolver(log LogFunc) *Resolver {
	return &Resolver{
		Client:    &http.Client{Timeout: 45 * time.Second},
		WatchBase: "https://www.youtube.com/watch?v=",
		NextURL:   "https://www.youtube.com/youtubei/v1/next?prettyPrint=false",
		OEmbedURL: "https://www.youtube.com/oembed?format=json&url=",
		UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
		Attempts:  3,
		Log:       log,
	}
}

// Wanted reports whether an upload is an art track worth resolving.
func (r *Resolver) Wanted(channel, uploader string) bool {
	return IsAutoGenerated(channel, uploader)
}

// Resolve returns the video id of the official music video linked from the
// given art track, or "" when none could be found. The returned reason is a
// short human readable explanation for logging.
func (r *Resolver) Resolve(videoID string) (string, string) {
	return r.ResolveLog(videoID, r.Log)
}

// ResolveLog is Resolve with a per-call log function, so concurrent
// callers can route messages to their own entry.
func (r *Resolver) ResolveLog(videoID string, logFn func(format string, a ...interface{})) (string, string) {
	logf := func(format string, a ...interface{}) {
		if logFn != nil {
			logFn(format+"\n", a...)
		}
	}
	var candidates []string

	// 1. Crawl the watch page like a browser would.
	html, err := r.get(r.WatchBase + videoID)
	if err != nil {
		logf("[official] %s: cannot fetch watch page: %v", videoID, err)
	} else {
		candidates = append(candidates, candidatesFromWatchPage(html, videoID)...)
	}

	// 2. The watch page sometimes ships a stripped down description panel.
	//    The innertube "next" call is what the page itself uses to fill it.
	if len(candidates) == 0 {
		nextJSON, err := r.fetchNext(videoID, html)
		if err != nil {
			logf("[official] %s: innertube next request failed: %v", videoID, err)
		} else {
			candidates = append(candidates, candidatesFromInitialData(nextJSON, videoID)...)
		}
	}

	if len(candidates) == 0 {
		return "", "no official video link found in description"
	}

	for _, cand := range uniqueStrings(candidates) {
		author, ok, err := r.lookupAuthor(cand)
		switch {
		case err != nil:
			// oEmbed can refuse (401) for videos that disallow embedding.
			// The link came from YouTube itself, so accept it.
			logf("[official] %s: oembed check for %s inconclusive (%v), accepting", videoID, cand, err)
			return cand, "linked from description (unverified channel)"
		case !ok:
			logf("[official] %s: candidate %s does not exist, skipping", videoID, cand)
		case IsTopicChannel(author):
			logf("[official] %s: candidate %s is another auto-generated track (%s), skipping", videoID, cand, author)
		default:
			return cand, fmt.Sprintf("official video by %q", author)
		}
	}

	return "", "linked videos were not official uploads"
}
