package official

import "testing"

func TestLooksLikeOfficialVideo(t *testing.T) {
	for _, title := range []string{
		"Hanson - MMMBop (Official Music Video)",
		"Nickelback - How You Remind Me [OFFICIAL VIDEO]",
		"INXS - Need You Tonight (Official Video)",
		"Song (Official HD Video)",
		"Band - Song (Music Video)",
	} {
		if !LooksLikeOfficialVideo(title) {
			t.Errorf("%q says it is the official video", title)
		}
	}
	for _, title := range []string{
		"Killer 2000",
		"Lovely Day",
		"Official Secrets", // not a video
		"Video Killed the Radio Star",
		"Song (Official Audio)",
	} {
		if LooksLikeOfficialVideo(title) {
			t.Errorf("%q does not say it is the official video", title)
		}
	}
}

func TestArtTrackFromVideoType(t *testing.T) {
	cases := []struct {
		tag             string
		artTrack, known bool
	}{
		{"ATV", true, true},
		{" atv ", true, true},
		{"OMV", false, true},
		{"UGC", false, true},
		{"OFFICIAL_SOURCE_MUSIC", true, true},
		{"", false, false},
	}
	for _, c := range cases {
		artTrack, known := ArtTrackFromVideoType(c.tag)
		if artTrack != c.artTrack || known != c.known {
			t.Errorf("ArtTrackFromVideoType(%q) = %v, %v; want %v, %v", c.tag, artTrack, known, c.artTrack, c.known)
		}
	}
}

func TestArtTrackFromPage(t *testing.T) {
	if !ArtTrackFromPage([]byte(`"shortDescription":"Provided to YouTube by Columbia\n\nLovely Day"`)) {
		t.Error("a description that starts with Provided to YouTube is an art track")
	}
	if !ArtTrackFromPage([]byte(`Auto-generated by YouTube.`)) {
		t.Error("an auto-generated description is an art track")
	}
	if ArtTrackFromPage([]byte(`"shortDescription":"Official video for the song. Subscribe!"`)) {
		t.Error("a normal description is not an art track")
	}
}
