package official

import (
	"bytes"
	"regexp"
	"strings"
)

var officialVideoTitle = regexp.MustCompile(`(?i)\b(official\s+(hd\s+|4k\s+)?(music\s+)?video|music\s+video)\b`)

// LooksLikeOfficialVideo reports whether a title already says the upload is the
// official video, so there is nothing to look up.
func LooksLikeOfficialVideo(title string) bool {
	return officialVideoTitle.MatchString(title)
}

// ArtTrackFromVideoType reads YouTube Music's tag for an upload: ATV is an
// auto-generated art track, any other tag (OMV, UGC, ...) is a real video.
// known is false when there is no tag.
func ArtTrackFromVideoType(videoType string) (artTrack, known bool) {
	switch strings.ToUpper(strings.TrimSpace(videoType)) {
	case "":
		return false, false
	case "ATV":
		return true, true
	default:
		return false, true
	}
}

// artTrackMarkers open the description of every auto-generated upload.
var artTrackMarkers = [][]byte{
	[]byte("Provided to YouTube by"),
	[]byte("Auto-generated by YouTube"),
}

// ArtTrackFromPage reports whether a watch page carries the description of an
// auto-generated art track.
func ArtTrackFromPage(page []byte) bool {
	for _, marker := range artTrackMarkers {
		if bytes.Contains(page, marker) {
			return true
		}
	}
	return false
}
