package official

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"strings"
	"sync"
	"testing"
)

func TestTopicChannel(t *testing.T) {
	if !IsTopicChannel("Armand Van Helden - Topic") {
		t.Error("a Topic channel should be recognised")
	}
	if IsTopicChannel("ModjoOfficial") {
		t.Error("an artist channel is not a Topic channel")
	}
}

// nextResponse builds an innertube "next" style document. musicID is the
// video linked from the Music card, descID a watch link in the description
// text, relatedID a recommended video that must never be picked.
func nextResponse(selfID, musicID, descID, relatedID string) []byte {
	doc := map[string]interface{}{
		"contents": map[string]interface{}{
			"twoColumnWatchNextResults": map[string]interface{}{
				"secondaryResults": []interface{}{
					map[string]interface{}{"compactVideoRenderer": map[string]interface{}{"videoId": relatedID}},
				},
			},
		},
		"currentVideoEndpoint": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": selfID}},
		"engagementPanels": []interface{}{
			map[string]interface{}{
				"engagementPanelSectionListRenderer": map[string]interface{}{
					"panelIdentifier": "engagement-panel-structured-description",
					"content": map[string]interface{}{
						"structuredDescriptionContentRenderer": map[string]interface{}{
							"items": []interface{}{
								map[string]interface{}{
									"expandableVideoDescriptionBodyRenderer": map[string]interface{}{
										"attributedDescriptionBodyText": map[string]interface{}{
											"content": "Provided to YouTube.\nOfficial video: https://youtu.be/" + descID + "\nAuto-generated by YouTube.",
											"commandRuns": []interface{}{
												map[string]interface{}{"onTap": map[string]interface{}{"innertubeCommand": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": descID}}}},
											},
										},
									},
								},
								map[string]interface{}{
									"videoDescriptionMusicSectionRenderer": map[string]interface{}{
										"sectionTitle": map[string]interface{}{"simpleText": "Music"},
										"carouselLockups": []interface{}{
											map[string]interface{}{
												"carouselLockupRenderer": map[string]interface{}{
													"videoLockup": map[string]interface{}{
														"compactVideoRenderer": map[string]interface{}{
															"videoId":            musicID,
															"navigationEndpoint": map[string]interface{}{"watchEndpoint": map[string]interface{}{"videoId": musicID}},
														},
													},
													"infoRows": []interface{}{
														map[string]interface{}{"infoRowRenderer": map[string]interface{}{"title": map[string]interface{}{"simpleText": "SONG"}}},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
	b, _ := json.Marshal(doc)
	return b
}

func TestCandidatesFromInitialData(t *testing.T) {
	raw := nextResponse("rnlp_avexYQ", "-bsONE-kZwI", "dEsCrIpTi0n", "rElAtEd0000")
	got := candidatesFromInitialData(raw, "rnlp_avexYQ")
	want := []string{"-bsONE-kZwI", "dEsCrIpTi0n"}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Fatalf("want %v, got %v", want, got)
	}

	// Music card pointing at the video itself must be ignored.
	raw = nextResponse("rnlp_avexYQ", "rnlp_avexYQ", "", "rElAtEd0000")
	if got := candidatesFromInitialData(raw, "rnlp_avexYQ"); len(got) != 0 {
		t.Fatalf("self link should be ignored, got %v", got)
	}
}

func watchPage(selfID, musicID, descID string) string {
	initial := string(nextResponse(selfID, musicID, descID, "rElAtEd0000"))
	player := `{"videoDetails":{"videoId":"` + selfID + `","shortDescription":"Tricky };</script> inside a string\nhttps://www.youtube.com/watch?v=` + descID + `&t=1"}}`
	return `<!DOCTYPE html><html><head><script>ytcfg.set({"INNERTUBE_CONTEXT":{"client":{"clientName":"WEB","clientVersion":"2.20261001.01.00"}},"INNERTUBE_CONTEXT_CLIENT_NAME":1});</script>` +
		`<script>var ytInitialPlayerResponse = ` + player + `;</script>` +
		`<script>var ytInitialData = ` + initial + `;</script></head><body></body></html>`
}

func TestCandidatesFromWatchPage(t *testing.T) {
	got := candidatesFromWatchPage([]byte(watchPage("rnlp_avexYQ", "-bsONE-kZwI", "dEsCrIpTi0n")), "rnlp_avexYQ")
	want := []string{"-bsONE-kZwI", "dEsCrIpTi0n"}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Fatalf("want %v, got %v", want, got)
	}

	stripped := `<script>var ytInitialPlayerResponse = {"videoDetails":{"shortDescription":"nothing here"}};</script>`
	if got := candidatesFromWatchPage([]byte(stripped), "rnlp_avexYQ"); len(got) != 0 {
		t.Fatalf("expected no candidates, got %v", got)
	}
}

func TestExtractJSONAfter(t *testing.T) {
	if extractJSONAfter([]byte("no marker"), "var x = ") != nil {
		t.Error("missing marker must return nil")
	}
	got := extractJSONAfter([]byte(`var x = {"a":"};</script>","b":[1,2]};</script>`), "var x = ")
	if string(got) != `{"a":"};</script>","b":[1,2]}` {
		t.Errorf("unexpected value: %s", got)
	}
}

// fakeYouTube serves a watch page, the innertube next endpoint and oEmbed.
type fakeYouTube struct {
	pages   map[string]string // video id -> watch page HTML
	next    map[string][]byte // video id -> next response
	authors map[string]string // video id -> channel name (missing = 404)
	titles  map[string]string // video id -> title the oEmbed answer carries
	mu      sync.Mutex
	hits    map[string]int
}

func (f *fakeYouTube) hit(name string) {
	f.mu.Lock()
	f.hits[name]++
	f.mu.Unlock()
}

func (f *fakeYouTube) count(name string) int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.hits[name]
}

func (f *fakeYouTube) server(t *testing.T) (*httptest.Server, *Resolver) {
	f.hits = map[string]int{}
	mux := http.NewServeMux()
	mux.HandleFunc("/watch", func(w http.ResponseWriter, r *http.Request) {
		id := r.URL.Query().Get("v")
		f.hit("watch")
		if page, ok := f.pages[id]; ok {
			_, _ = w.Write([]byte(page))
			return
		}
		http.NotFound(w, r)
	})
	mux.HandleFunc("/youtubei/v1/next", func(w http.ResponseWriter, r *http.Request) {
		f.hit("next")
		var body struct {
			VideoID string `json:"videoId"`
		}
		_ = json.NewDecoder(r.Body).Decode(&body)
		if r.Header.Get("X-YouTube-Client-Version") == "" {
			t.Errorf("next request without client version header")
		}
		if resp, ok := f.next[body.VideoID]; ok {
			_, _ = w.Write(resp)
			return
		}
		_, _ = w.Write([]byte(`{}`))
	})
	mux.HandleFunc("/oembed", func(w http.ResponseWriter, r *http.Request) {
		f.hit("oembed")
		u := r.URL.Query().Get("url")
		id := u[strings.LastIndex(u, "=")+1:]
		if author, ok := f.authors[id]; ok {
			_ = json.NewEncoder(w).Encode(map[string]string{"author_name": author, "title": f.titles[id]})
			return
		}
		http.NotFound(w, r)
	})
	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)

	res := NewResolver(func(string, ...interface{}) {})
	res.Client = srv.Client()
	res.WatchBase = srv.URL + "/watch?v="
	res.NextURL = srv.URL + "/youtubei/v1/next"
	res.OEmbedURL = srv.URL + "/oembed?format=json&url="
	res.Attempts = 1
	return srv, res
}

func TestResolveFromWatchPage(t *testing.T) {
	f := &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "-bsONE-kZwI", "")},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res := f.server(t)
	got, reason := res.Resolve("rnlp_avexYQ")
	if got != "-bsONE-kZwI" {
		t.Fatalf("want -bsONE-kZwI, got %q (%s)", got, reason)
	}
	if f.count("next") != 0 {
		t.Errorf("next endpoint should not be needed when the page has the Music card")
	}
	if !res.Wanted("Song", "Artist - Topic", "") || !res.Wanted("Song", "Band", "Band") {
		t.Error("every upload is worth a lookup, whatever its channel is called")
	}
	if res.Wanted("Band - Song (Official Video)", "Band", "Band") {
		t.Error("an upload whose title says official video needs no lookup")
	}
}

func TestResolveFallsBackToNext(t *testing.T) {
	f := &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": `<script>var ytInitialPlayerResponse = {"videoDetails":{"shortDescription":"stripped"}};</script>`},
		next:    map[string][]byte{"rnlp_avexYQ": nextResponse("rnlp_avexYQ", "-bsONE-kZwI", "", "rElAtEd0000")},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res := f.server(t)
	got, reason := res.Resolve("rnlp_avexYQ")
	if got != "-bsONE-kZwI" {
		t.Fatalf("want -bsONE-kZwI, got %q (%s)", got, reason)
	}
	if n := f.count("next"); n != 1 {
		t.Errorf("expected one next request, got %d", n)
	}
}

func TestResolveSkipsTopicAndDeadLinks(t *testing.T) {
	f := &fakeYouTube{
		pages: map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "aNoThErT0p1", "dEsCrIpTi0n")},
		authors: map[string]string{
			"aNoThErT0p1": "Armand Van Helden - Topic",
			"dEsCrIpTi0n": "Armand Van Helden",
		},
	}
	_, res := f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "dEsCrIpTi0n" {
		t.Fatalf("Topic candidate should be skipped in favour of the description link, got %q", got)
	}

	f = &fakeYouTube{pages: map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "gOnEgOnEgOn", "")}}
	_, res = f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "" {
		t.Fatalf("dead candidate must not be returned, got %q", got)
	}

	f = &fakeYouTube{}
	_, res = f.server(t)
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "" {
		t.Fatalf("expected empty result, got %q", got)
	}
}

func TestResolveThroughDumper(t *testing.T) {
	// Direct fetch and next are stripped; the dumper hands over a full page.
	f := &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": `<script>var ytInitialPlayerResponse = {"videoDetails":{"shortDescription":"stripped"}};</script>`},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res := f.server(t)
	dumped := 0
	res.Dumper = func(videoID string) ([]DumpedPage, error) {
		dumped++
		return []DumpedPage{
			{URL: "https://www.youtube.com/watch?v=" + videoID, Body: []byte(watchPage(videoID, "-bsONE-kZwI", ""))},
			{URL: "https://www.youtube.com/youtubei/v1/player?prettyPrint=false", Body: []byte(`{}`)},
		}, nil
	}
	got, reason := res.Resolve("rnlp_avexYQ")
	if got != "-bsONE-kZwI" || dumped != 1 {
		t.Fatalf("want -bsONE-kZwI via dumper, got %q (%s), dumped=%d", got, reason, dumped)
	}

	// With a Music card on the direct page the dumper is never called.
	f = &fakeYouTube{
		pages:   map[string]string{"rnlp_avexYQ": watchPage("rnlp_avexYQ", "-bsONE-kZwI", "")},
		authors: map[string]string{"-bsONE-kZwI": "London Records"},
	}
	_, res = f.server(t)
	res.Dumper = func(string) ([]DumpedPage, error) { t.Error("dumper should not run"); return nil, nil }
	if got, _ := res.Resolve("rnlp_avexYQ"); got != "-bsONE-kZwI" {
		t.Fatalf("direct path broken: %q", got)
	}
}

func TestLoadCookieJar(t *testing.T) {
	path := t.TempDir() + "/cookies.txt"
	content := "# Netscape HTTP Cookie File\n# comment\n\n.youtube.com\tTRUE\t/\tTRUE\t0\tSOCS\tCAI\n#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t4102444800\tSID\tsecret\nexample.com\tFALSE\t/\tFALSE\t0\tother\tx\nbroken line\n"
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
	jar, n, err := LoadCookieJar(path)
	if err != nil || n != 3 {
		t.Fatalf("load failed: %v (n=%d)", err, n)
	}
	u, _ := url.Parse("https://www.youtube.com/watch?v=x")
	names := map[string]string{}
	for _, c := range jar.Cookies(u) {
		names[c.Name] = c.Value
	}
	if names["SID"] != "secret" || names["SOCS"] != "CAI" || names["other"] != "" {
		t.Errorf("unexpected cookies for youtube: %v", names)
	}

	res := NewResolver(nil)
	if n, err := res.UseCookies(path); err != nil || n != 3 || res.Client.Jar == nil {
		t.Errorf("UseCookies failed: %v %d", err, n)
	}
	if _, _, err := LoadCookieJar(t.TempDir() + "/missing.txt"); err == nil {
		t.Error("missing file should fail")
	}
	empty := t.TempDir() + "/empty.txt"
	if err := os.WriteFile(empty, []byte("# nothing\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if _, _, err := LoadCookieJar(empty); err == nil {
		t.Error("file without cookies should fail")
	}
}
