// Package official finds the official music video that YouTube links from
// the "Music" card in the description of an auto-generated art track.
package official

import "strings"

// IsTopicChannel reports whether a channel name is one of YouTube's
// auto-generated "<Artist> - Topic" channels (the art-track uploads).
func IsTopicChannel(name string) bool {
	return strings.HasSuffix(strings.TrimSpace(name), " - Topic")
}

// IsAutoGenerated reports whether an upload is an auto-generated art track
// (uploaded by a "- Topic" channel). With no channel information at all it
// returns true so the caller still tries to resolve.
func IsAutoGenerated(channel, uploader string) bool {
	if channel == "" && uploader == "" {
		return true
	}
	return IsTopicChannel(channel) || IsTopicChannel(uploader)
}
